-- КТО ПО ЖИЗНИ — Supabase schema v15
-- Выполните целиком в SQL Editor нового проекта Supabase.

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  nickname text unique not null check (char_length(nickname) between 3 and 24),
  bio text not null default '' check (char_length(bio) <= 240),
  avatar_url text,
  cover_url text,
  donation_total integer not null default 0 check (donation_total >= 0),
  subscription_active boolean not null default false,
  subscription_amount integer not null default 0 check (subscription_amount >= 0),
  subscription_expires_at timestamptz,
  created_at timestamptz not null default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  user_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 500),
  created_at timestamptz not null default now()
);

create index if not exists messages_created_at_idx on public.messages(created_at desc);
create index if not exists messages_user_id_idx on public.messages(user_id);

-- Профиль создаётся автоматически даже если включено подтверждение e-mail.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
declare
  wanted text;
begin
  wanted := nullif(trim(new.raw_user_meta_data->>'nickname'), '');
  if wanted is null or char_length(wanted) < 3 then
    wanted := 'Участник_' || substr(new.id::text, 1, 8);
  end if;
  if exists(select 1 from public.profiles where lower(nickname)=lower(wanted)) then
    wanted := left(wanted, 15) || '_' || substr(new.id::text, 1, 8);
  end if;
  insert into public.profiles(id,nickname) values(new.id,left(wanted,24))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

drop policy if exists "profiles readable" on public.profiles;
drop policy if exists "own profile update" on public.profiles;
drop policy if exists "messages readable" on public.messages;
drop policy if exists "auth can post" on public.messages;
drop policy if exists "own messages delete" on public.messages;

create policy "profiles readable" on public.profiles for select using (true);
create policy "own profile update" on public.profiles for update to authenticated
  using (auth.uid()=id) with check (auth.uid()=id);
create policy "messages readable" on public.messages for select using (true);
create policy "auth can post" on public.messages for insert to authenticated
  with check (auth.uid()=user_id);
create policy "own messages delete" on public.messages for delete to authenticated
  using (auth.uid()=user_id);

-- Пользователь может менять только обычные поля профиля.
revoke update on public.profiles from authenticated;
grant update (nickname,bio,avatar_url,cover_url) on public.profiles to authenticated;

-- Публичное хранилище аватаров/обложек. Записывать можно только в свою папку UUID/...
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types)
values ('profile-media','profile-media',true,5242880,array['image/png','image/jpeg','image/webp'])
on conflict (id) do update set
  public=excluded.public,
  file_size_limit=excluded.file_size_limit,
  allowed_mime_types=excluded.allowed_mime_types;

drop policy if exists "public profile media" on storage.objects;
drop policy if exists "upload own profile media" on storage.objects;
drop policy if exists "update own profile media" on storage.objects;
drop policy if exists "delete own profile media" on storage.objects;
create policy "public profile media" on storage.objects for select using (bucket_id='profile-media');
create policy "upload own profile media" on storage.objects for insert to authenticated
  with check (bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "update own profile media" on storage.objects for update to authenticated
  using (bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "delete own profile media" on storage.objects for delete to authenticated
  using (bucket_id='profile-media' and (storage.foldername(name))[1]=auth.uid()::text);

-- Realtime для общего чата.
do $$ begin
  alter publication supabase_realtime add table public.messages;
exception when duplicate_object then null;
end $$;

-- ВАЖНО: donation_total и subscription_* браузеру не выдаются на изменение.
-- Их позже меняет только доверенный webhook/Edge Function с service-role.
